<template><div><h2 id="why-to-learn-operating-system" tabindex="-1"><a class="header-anchor" href="#why-to-learn-operating-system"><span>Why to Learn Operating System?</span></a></h2>
<p>All software applications are built on operating system. The very first idea of operating system was to serve all kinds of applications better and faster. The basic method is to <strong>build abstractions</strong>.</p>
<h2 id="what-is-operating-system" tabindex="-1"><a class="header-anchor" href="#what-is-operating-system"><span>What is Operating System?</span></a></h2>
<blockquote>
<p>Operating System: A body of software, in fact, that is responsible for making it easy to run programs (even allowing you to seemingly run many at the same time), allowing programs to share memory, enabling programs to interact with devices, and other fun stuff like that. (OSTEP)</p>
</blockquote>
<p>Operating system is a special piece of software that is in charge of making sure the system operates correctly and efficiently in an <strong>easy-to-use</strong> manner. The early name for the OS was <em>supervisor</em> or even the <em>master control program</em>, you can feel why do we need it.</p>
<p>In a broad sense, if a particular software possess the above property, we can call it an &quot;operating system&quot;. For example, is Wechat an operating sysytem?</p>
<p>The <strong>three easy pieces</strong> of an OS is that: <strong>Virtualization</strong>, <strong>Concurrency</strong>, <strong>Persistence</strong>.</p>
<h2 id="how-does-os-make-the-system-easy-to-use" tabindex="-1"><a class="header-anchor" href="#how-does-os-make-the-system-easy-to-use"><span>How does OS Make the System Easy to Use?</span></a></h2>
<h3 id="virtualization" tabindex="-1"><a class="header-anchor" href="#virtualization"><span>Virtualization</span></a></h3>
<p>Virtualization, that is, the OS takes a physical resource (such as the CPU, memory, or a disk) and transforms it into a more general, powerful, and easy-to-use <strong>virtual</strong> form of itself. Sometimes we refer to OS as a <strong>virtual machine</strong>.</p>
<p><strong>Virtualizing the CPU</strong> means that the OS, with some help of hardware, is in charge of the <strong>illusion</strong> that the system has a very large number of virtual CPUs instead of just one CPU, allowing many programs to seemingly run at once.</p>
<p><strong>Virtualizing memory</strong> means that each process accesses its own <strong>private virtual address space</strong>, which the OS somehow maps onto the physical memory of the machine. A memory reference within one running program does not affect the address space of other processes; as far as the running process is concerned, it has physical memory all to itself. The reality, however, is that physical memory is a shared resource, managed by OS.</p>
<p>The model of physical memory is just an array of bytes. To read memory, one must specify an <strong>address</strong> to be able to access the data stored there; to write memory, one must also specify the <strong>data</strong> to be written to the given address.</p>
<h3 id="service-provider" tabindex="-1"><a class="header-anchor" href="#service-provider"><span>Service Provider</span></a></h3>
<p>In order to allow users to tell the OS what to do and thus make use of the features of the virtual machine, the OS provides a <strong>standard library</strong> (<strong>system calls</strong>) to applications.</p>
<p><strong>Every program is a state machine</strong>. It always starts from being loaded by OS, set up to default state through <code v-pre>execve</code> from another process; and then the state machine operates a bunch of operations (computations + syscalls); finally <code v-pre>_exit</code> is called.</p>
<p>OS is an API provider providing <code v-pre>syscalls</code> for softwares.</p>
<h3 id="resource-manager" tabindex="-1"><a class="header-anchor" href="#resource-manager"><span>Resource Manager</span></a></h3>
<p>Because virtualization allows many programs to run (<strong>sharing CPU</strong>), and to concurrently access their own instructions and data (<strong>sharing memory</strong>), and to access devices (<strong>sharing disks and so forth</strong>), the OS is known as a <strong>resource manager</strong>.</p>
<h2 id="concurrency" tabindex="-1"><a class="header-anchor" href="#concurrency"><span>Concurrency</span></a></h2>
<p>The problem of <strong>concurrency</strong> refers to a host of problems that arise, and must be addressed, when working on many things at once in the same program. The problems of concurrency are no longer limited to the OS, The modern <strong>multi-threaded</strong> programs exhibit the same problems.</p>
<p>The following program shows an example of concurrency problem. The reason for the strange behavior relates to how instructions are executed, which is one at a time. The key part of the program <code v-pre>counter++</code> takes three instructions: one to load the value of the <code v-pre>counter</code> from memory into a register, one to increment it, and one to store it back into memory. Because these three instructions do not execute <strong>atomically</strong>, problems arise.</p>
<div class="hint-container warning">
<p class="hint-container-title">The Problem</p>
<p>When there are many concurrently executing threads within the same memory space, how can we build a correctly working program?<br>
What primitives are needed from the OS?<br>
What mechanisms should be provided by the hardware?<br>
How can we use them to solve the problems of concurrency?</p>
</div>
<div class="language-c line-numbers-mode" data-highlighter="shiki" data-ext="c" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-c"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">// thread.c</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">#include</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> &#x3C;stdio.h></span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">#include</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> &#x3C;stdlib.h></span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">#include</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "common.h"</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">volatile</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> counter </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> loops;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">void</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> *</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">worker</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">void</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> *</span><span style="--shiki-light:#383A42;--shiki-light-font-style:inherit;--shiki-dark:#E06C75;--shiki-dark-font-style:italic">arg</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) {</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">  int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> i;</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">  for</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (i </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">; i </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">&#x3C;</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> loops; i</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">++</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) {</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    counter</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">++</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  }</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">  return</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> NULL</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">}</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">int</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> main</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">int</span><span style="--shiki-light:#383A42;--shiki-light-font-style:inherit;--shiki-dark:#E06C75;--shiki-dark-font-style:italic"> argc</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> char</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> *</span><span style="--shiki-light:#383A42;--shiki-light-font-style:inherit;--shiki-dark:#E06C75;--shiki-dark-font-style:italic">argv</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">[]</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) {</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">  if</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (argc </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">!=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) {</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    fprintf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(stderr, </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"usage: threads &#x3C;value></span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\n</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">    exit</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  }</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  loops </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">=</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> atoi</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">argv</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">]);</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">  pthread_t</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> p1, p2;</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">  printf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"Initial value : </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">%d</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\n</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, counter);</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">  Pthread_create</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">&#x26;</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">p1, </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">NULL</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, worker, </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">NULL</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">  Pthread_create</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">&#x26;</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">p2, </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">NULL</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, worker, </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">NULL</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">  Pthread_join</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(p1, </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">NULL</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">  Pthread_join</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(p2, </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">NULL</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">  printf</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"Final value : </span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">%d</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\n</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, counter);</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">  return</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">prompt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./thread</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 100000</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Initial</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> value</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> :</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Final</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> value</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   :</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 143012</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">prompt</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">> </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">./thread</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 100000</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Initial</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> value</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> :</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Final</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> value</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   :</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 137298</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="persistence" tabindex="-1"><a class="header-anchor" href="#persistence"><span>Persistence</span></a></h2>
<p>In system memory, data can be easily lost, as devices such as DRAM store values in a volatile manner; when power goes away or the system crashes, any data in memory is lost. Thus, we need hardware and software to be able to store data persistently; such storage is thus critical to any system as users care a great deal about their data.</p>
<p>The hardware comes in the form of some kind of input/output or I/O device; in modern systems, a hard drive is a common repository for long-lived information. The software in the operating system that usually manages the disk is called the <strong>file system</strong>; it is thus responsible for storing any files the user creates in a reliable and efficient manner on the disks of the system. Unlike the abstractions provided by the OS for the CPU and memory, the OS does not create a private, virtualized disk for each application. Rather, it is assumed that often times, users will want to <strong>share</strong> information that is in files.</p>
<div class="hint-container warning">
<p class="hint-container-title">The Problem</p>
<p>The file system is the part of the OS in charge of managing persistent data.<br>
What techniques are needed to do so correctly?<br>
What mechanisms and policies are required to do so with high performance?<br>
How is reliability achieved, in the face of failures in hardware and software?</p>
</div>
<h2 id="design-goals" tabindex="-1"><a class="header-anchor" href="#design-goals"><span>Design Goals</span></a></h2>
<ul>
<li>Abstraction</li>
<li>Multiprogramming</li>
<li>Isolation</li>
<li>Sharing</li>
<li>Security</li>
<li>Performance</li>
<li>Range of uses</li>
<li>Reliability</li>
<li>Balance the trade-offs</li>
</ul>
<p>Any operating system must multiplex processes onto the underlying hardware, isolate processes from each other, and provide mechanisms for controlled inter-process communication.</p>
<h2 id="history-of-operating-system" tabindex="-1"><a class="header-anchor" href="#history-of-operating-system"><span>History of Operating System</span></a></h2>
<p>Batch processing (Just libraries) -&gt; System call (protection) -&gt; Multiprogramming -&gt; PC (networking, windowing systems, user-level threads, drivers. etc.)</p>
<blockquote>
<p>Read Section 2.6 in Chapter Introduction in OSTEP.</p>
</blockquote>
</div></template>


