<template><div><h2 id="clarification" tabindex="-1"><a class="header-anchor" href="#clarification"><span>Clarification</span></a></h2>
<p>Okay, so first I’ll restate the problem to make sure I understand it correctly.</p>
<p>We are given an integer array <code v-pre>nums</code>, and we need to return the majority element, meaning the element that appears more than 50%. And the problem guarantees that such an element always exists, which also means it won't be an empty array.</p>
<p>For example, if <code v-pre>nums = [3,2,3]</code>, the answer is <code v-pre>3</code>, because it appears twice out of three elements.</p>
<p>What is the most important value of the problem? is it time or space?</p>
<h2 id="brute-force-approach" tabindex="-1"><a class="header-anchor" href="#brute-force-approach"><span>Brute-force Approach</span></a></h2>
<p>One approach is to use a hash map to count frequencies of each element during the loop of the array. That gives us <code v-pre>O(n)</code> time, but it uses <code v-pre>O(n)</code> space.</p>
<p>Another approach is to sort the array first and then find the most frequent element while looping over the sorted array. The time complexity will increase to <code v-pre>O(nlogn)</code> but it doesn't need extra space.</p>
<h2 id="optimized-approach" tabindex="-1"><a class="header-anchor" href="#optimized-approach"><span>Optimized Approach</span></a></h2>
<p>The optimal approach here is Boyer-Moore Voting Algorithm. The idea is: since the majority element appears more than the half, it should be able to “cancel out” all other elements and still remain as the final candidate, like the Shisen-sho game. But instead of connecting the same mahjong tiles, we do a cancellation when there is a difference here.</p>
<p>So what I'll do is to repeatedly cancel different elements against each other. I track a candidate and a vote count. Matching elements increase the count, non-matching elements decrease it by one, and whenever the count reaches zero I pick a new candidate. After one loop, the surviving candidate must be the majority element. This gives <code v-pre>O(n)</code> time and <code v-pre>O(1)</code> space.</p>
<h2 id="code" tabindex="-1"><a class="header-anchor" href="#code"><span>Code</span></a></h2>
<div class="language-java line-numbers-mode" data-highlighter="shiki" data-ext="java" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-java"><span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">class</span><span style="--shiki-light:#C18401;--shiki-dark:#E5C07B"> Solution</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    public</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> int</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF"> majorityElement</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#C18401;--shiki-dark:#C678DD">int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[] </span><span style="--shiki-light:#383A42;--shiki-light-font-style:inherit;--shiki-dark:#E06C75;--shiki-dark-font-style:italic">nums</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> {</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">        int</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> candidate</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> =</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, vote </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">        for</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">int</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75"> num</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> :</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> nums) {</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">            if</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (vote </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">==</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)          candidate </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> num;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">            if</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> (candidate </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">==</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> num)   vote++;</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">            else</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">                    vote--;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        }</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">        return</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> candidate;</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    }</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="follow-up" tabindex="-1"><a class="header-anchor" href="#follow-up"><span>Follow-up</span></a></h2>
<p>One follow-up I would mention is: if the majority element is not guaranteed, then after finding the candidate, I would do a second pass to verify its frequency is actually greater than the half.</p>
</div></template>


